cargo-features = ["profile-rustflags"]

[workspace]
members = [
    "src/rimca",
    "src/librimca",
]

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
strip = true
rustflags= [ "target-cpu=native" ]
