cargo-features = ["strip"]

[package]
name = "librimca"
version = "0.1.0"
authors = ["liabri"]
edition = "2021"

[lib]
name = "rimca"
path = "src/lib.rs"
crate-type = ["rlib"]

[dependencies]
serde_json = "1.0.79"
serde = { version = "1.0.136", features = [ "derive" ] }
reqwest = { version = "0.11.0", features = ["blocking", "json"] }

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
strip = true 