[package]
name = "rimca"
version = "0.2.0"
edition = "2021"

[dependencies]
librimca = { path = "../librimca" }
structopt = "0.3.25"
anyhow = "1.0.65"
confy = "0.5.0"
serde = "1.0.145"
directories-next = "2.0.0"